# ─────────────────────────────────────────────────────────────────────────────
# WinTaskPro Project Cleaner  v1.0
# Drop in project root and run:
#   powershell -ExecutionPolicy Bypass -File clean_project.ps1
#
# Flags (for automation / CI — skip the interactive menu):
#   -Execute              Clean build artifacts without prompts
#   -Execute -Aggressive  Also remove *.bak, *.orig, *.old, *.log, *.tmp
#   -Backup               Create a source backup zip and exit
# ─────────────────────────────────────────────────────────────────────────────
param(
    [switch] $Execute,
    [switch] $Aggressive,
    [switch] $Backup
)

Set-StrictMode -Version Latest
# NOTE: Do NOT set $ErrorActionPreference = 'Stop' here.
# Filesystem walks hit permission-denied on git/node internals and would abort.

$Host.UI.RawUI.WindowTitle = "WinTaskPro Project Cleaner"

# ── Output helpers ─────────────────────────────────────────────────────────────
function Write-Ok   { param($msg) Write-Host "  [OK]  $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "  [!!]  $msg" -ForegroundColor Yellow }
function Write-Info { param($msg) Write-Host "   -   $msg" -ForegroundColor Cyan }
function Write-Bad  { param($msg) Write-Host "  [!!]  $msg" -ForegroundColor Red }
function Write-Bold { param($msg) Write-Host "  $msg" -ForegroundColor White }
function Write-Dim  { param($msg) Write-Host "  $msg" -ForegroundColor DarkGray }
function Write-Sep  { Write-Host "  ──────────────────────────────────────────────────" -ForegroundColor DarkGray }

function Write-Header {
    Clear-Host
    Write-Host ""
    Write-Host "  ██╗    ██╗████████╗██████╗ " -ForegroundColor Cyan
    Write-Host "  ██║    ██║╚══██╔══╝██╔══██╗" -ForegroundColor Cyan
    Write-Host "  ██║ █╗ ██║   ██║   ██████╔╝" -ForegroundColor Cyan
    Write-Host "  ██║███╗██║   ██║   ██╔═══╝ " -ForegroundColor Cyan
    Write-Host "  ╚███╔███╔╝   ██║   ██║     " -ForegroundColor Cyan
    Write-Host "   ╚══╝╚══╝    ╚═╝   ╚═╝     " -ForegroundColor Cyan
    Write-Host "  WinTaskPro — Project Cleaner  v1.0" -ForegroundColor DarkGray
    Write-Host "  ──────────────────────────────────" -ForegroundColor DarkGray
    Write-Host ""
}

# ── Keyboard helpers ───────────────────────────────────────────────────────────
function Confirm-Action {
    param($prompt)
    Write-Host ""
    Write-Host "  $prompt [Y/N] " -ForegroundColor Yellow -NoNewline
    $k = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    Write-Host $k.Character
    return ($k.Character -eq 'y' -or $k.Character -eq 'Y')
}

function Press-Any {
    Write-Host ""
    Write-Host "  Press any key to continue..." -ForegroundColor DarkGray
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
}

# ── Size helpers ───────────────────────────────────────────────────────────────
function Get-FolderSize {
    param($path)
    if (-not (Test-Path $path)) { return 0 }
    $sum = (Get-ChildItem $path -Recurse -File -ErrorAction SilentlyContinue |
            Measure-Object -Property Length -Sum).Sum
    if ($null -eq $sum) { return 0 }
    return $sum
}

function Format-Size {
    param([long] $bytes)
    if ($bytes -ge 1GB) { return "{0:N1} GB" -f ($bytes / 1GB) }
    if ($bytes -ge 1MB) { return "{0:N1} MB" -f ($bytes / 1MB) }
    if ($bytes -ge 1KB) { return "{0:N0} KB" -f ($bytes / 1KB) }
    return "$bytes B"
}

# ── Config ─────────────────────────────────────────────────────────────────────
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$ArchiveDir  = Join-Path $ProjectRoot "_archive"

# Files that must never be deleted by this cleaner
$ProtectedFiles = @(
    "clean_project.ps1", "devserver.js",
    "README.md", "CHANGELOG.md", "AGENT_RULES.md",
    "HANDOVER.md", "SETUP.md", "UPDATER.md",
    ".gitignore", "package.json", "package-lock.json"
)
$ProtectedDirs = @(".git", "src", "src-tauri")

# Files to health-check
$EssentialFiles = @(
    "package.json", "devserver.js",
    "src\index.html", "src\app.js", "src\style.css",
    "README.md", "CHANGELOG.md", "AGENT_RULES.md"
)

$EssentialRustFiles = @(
    "src-tauri\src\main.rs",
    "src-tauri\src\scheduler.rs",
    "src-tauri\Cargo.toml",
    "src-tauri\tauri.conf.json",
    "src-tauri\capabilities\default.json"
)

$EssentialDirs = @(
    "src", "src-tauri", "src-tauri\src",
    "src-tauri\capabilities", "src-tauri\icons"
)

# Directories that can be safely deleted (regenerated by build)
$CleanableDirs = @(
    @{ Name = "src-tauri\target"; Label = "Rust build artifacts (src-tauri/target/)"; UseCargoClear = $true },
    @{ Name = "node_modules";    Label = "NPM packages (node_modules/)";              UseCargoClear = $false }
)

# Temp/backup file extensions (Aggressive mode)
$TempExtensions  = @(".log", ".tmp", ".swp")
$TempExact       = @("Thumbs.db", ".DS_Store", "desktop.ini")
$AggressiveExts  = @(".bak", ".orig", ".old", ".backup", ".pyc")
$AggressiveSuffix = "~"

# ── Functions ──────────────────────────────────────────────────────────────────

function Show-ProjectHealth {
    Write-Header
    Write-Bold "PROJECT HEALTH CHECK"
    Write-Sep
    Write-Host ""
    Write-Info "Root: $ProjectRoot"
    Write-Host ""

    $missing = 0

    Write-Bold "Core files:"
    foreach ($f in $EssentialFiles) {
        $p = Join-Path $ProjectRoot $f
        if (Test-Path $p) {
            $sz = (Get-Item $p).Length
            Write-Ok "$f  ($(Format-Size $sz))"
        } else {
            Write-Bad "$f  — MISSING"
            $missing++
        }
    }

    Write-Host ""
    Write-Bold "Rust / Tauri source files:"
    foreach ($f in $EssentialRustFiles) {
        $p = Join-Path $ProjectRoot $f
        if (Test-Path $p) {
            $lines = (Get-Content $p -ErrorAction SilentlyContinue | Measure-Object -Line).Lines
            Write-Ok "$f  ($lines lines)"
        } else {
            Write-Bad "$f  — MISSING"
            $missing++
        }
    }

    Write-Host ""
    Write-Bold "Essential directories:"
    foreach ($d in $EssentialDirs) {
        $p = Join-Path $ProjectRoot $d
        if (Test-Path $p) {
            $count = (Get-ChildItem $p -Recurse -File -ErrorAction SilentlyContinue | Measure-Object).Count
            Write-Ok "$d\  ($count files)"
        } else {
            Write-Bad "$d\  — MISSING"
            $missing++
        }
    }

    Write-Host ""
    Write-Bold "Build tools:"
    $cargoOk = $null -ne (Get-Command "cargo" -ErrorAction SilentlyContinue)
    $nodeOk  = $null -ne (Get-Command "node"  -ErrorAction SilentlyContinue)
    $npmOk   = $null -ne (Get-Command "npm"   -ErrorAction SilentlyContinue)
    if ($cargoOk) { Write-Ok  "cargo  $(cargo --version 2>$null)" }
    else          { Write-Bad "cargo  — NOT FOUND  (install Rust: rustup.rs)" }
    if ($nodeOk)  { Write-Ok  "node   $(node --version 2>$null)" }
    else          { Write-Bad "node   — NOT FOUND  (install Node.js)" }
    if ($npmOk)   { Write-Ok  "npm    $(npm --version 2>$null)" }
    else          { Write-Bad "npm    — NOT FOUND" }

    Write-Host ""
    $nmPath = Join-Path $ProjectRoot "node_modules"
    if (Test-Path $nmPath) { Write-Ok  "node_modules\ installed" }
    else                   { Write-Warn "node_modules\ missing — run 'npm install' before building" }

    Write-Host ""
    Write-Bold "Version info:"
    $pkgPath = Join-Path $ProjectRoot "package.json"
    if (Test-Path $pkgPath) {
        $pkg = Get-Content $pkgPath -Raw | ConvertFrom-Json
        Write-Info ("package.json         v" + $pkg.version)
    }
    $cargoPath = Join-Path $ProjectRoot "src-tauri\Cargo.toml"
    if (Test-Path $cargoPath) {
        $verLine = Select-String -Path $cargoPath -Pattern '^version = "(.+)"' | Select-Object -First 1
        if ($verLine) {
            Write-Info ("src-tauri/Cargo.toml v" + $verLine.Matches[0].Groups[1].Value)
        }
    }
    $tauriPath = Join-Path $ProjectRoot "src-tauri\tauri.conf.json"
    if (Test-Path $tauriPath) {
        $tauri = Get-Content $tauriPath -Raw | ConvertFrom-Json
        Write-Info ("tauri.conf.json      v" + $tauri.version)
    }

    Write-Host ""
    if ($missing -eq 0) { Write-Ok  "All essential files present. Project looks healthy." }
    else                { Write-Bad "$missing essential file(s) MISSING — project may not build." }

    Press-Any
}

function Show-DiskUsage {
    Write-Header
    Write-Bold "DISK USAGE"
    Write-Sep
    Write-Host ""
    Write-Info "Scanning (may take a moment for large target/ folders)..."
    Write-Host ""

    $total = 0
    $items = @()

    Get-ChildItem $ProjectRoot -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        $sz = Get-FolderSize $_.FullName
        $total += $sz
        $items += [PSCustomObject]@{ Name = "$($_.Name)/"; Size = $sz; Kind = "dir" }
    }
    Get-ChildItem $ProjectRoot -File -ErrorAction SilentlyContinue | ForEach-Object {
        $sz = $_.Length
        $total += $sz
        $items += [PSCustomObject]@{ Name = $_.Name; Size = $sz; Kind = "file" }
    }

    $items  = $items | Sort-Object Size -Descending
    $maxSz  = ($items | Measure-Object Size -Maximum).Maximum
    if ($null -eq $maxSz -or $maxSz -eq 0) { $maxSz = 1 }
    $maxBar = 42

    foreach ($item in $items) {
        $bar     = [math]::Round($item.Size / $maxSz * $maxBar)
        $barStr  = [string]::new([char]0x2588, $bar)
        $padStr  = [string]::new([char]0x00B7, ($maxBar - $bar))
        $sizeStr = (Format-Size $item.Size).PadLeft(9)
        $nameStr = $item.Name.PadRight(26)

        # Colour-code by type
        $cleanable = $CleanableDirs | Where-Object { $item.Name -eq "$($_.Name.Split('\')[-1])/" -or $item.Name -eq "$($_.Name)/" }
        if ($cleanable)              { $col = "Yellow" }
        elseif ($item.Kind -eq "dir") { $col = "Cyan"   }
        else                         { $col = "Gray"    }

        Write-Host "  $nameStr" -NoNewline -ForegroundColor $col
        Write-Host " $sizeStr  " -NoNewline -ForegroundColor White
        Write-Host $barStr -NoNewline -ForegroundColor DarkMagenta
        Write-Host $padStr -ForegroundColor DarkGray
    }

    Write-Host ""
    Write-Sep
    Write-Host ("  " + "TOTAL".PadRight(26) + (Format-Size $total).PadLeft(9)) -ForegroundColor White
    Write-Host ""
    Write-Host "  " -NoNewline
    Write-Host [char]0x2588 -NoNewline -ForegroundColor DarkMagenta
    Write-Host " = cleanable build artifacts   " -NoNewline -ForegroundColor Yellow
    Write-Host [char]0x2588 -NoNewline -ForegroundColor Cyan
    Write-Host " = source files" -ForegroundColor Cyan

    Press-Any
}

function Show-TempFiles {
    Write-Header
    Write-Bold "TEMP & BACKUP FILES"
    Write-Sep
    Write-Host ""

    $found = @()
    $exts = $TempExtensions + $AggressiveExts
    Get-ChildItem $ProjectRoot -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel  = $_.FullName.Substring($ProjectRoot.Length)
        if ($rel.Length -gt 0 -and ($rel[0] -eq '\' -or $rel[0] -eq '/')) { $rel = $rel.Substring(1) }
        $skip = $false
        foreach ($pf in $ProtectedFiles) { if ($_.Name -eq $pf) { $skip = $true; break } }
        foreach ($pd in $ProtectedDirs)  { if ($rel.StartsWith($pd + '\') -or $rel.StartsWith($pd + '/')) { $skip = $true; break } }
        if ($skip) { return }
        $ext = $_.Extension.ToLower()
        $isTemp = ($exts -contains $ext) -or ($TempExact -contains $_.Name) -or $_.Name.EndsWith($AggressiveSuffix)
        if ($isTemp) {
            $found += [PSCustomObject]@{ Path = $_.FullName; Rel = $rel; Size = $_.Length }
        }
    }

    if ($found.Count -eq 0) {
        Write-Ok "No temp or backup files found."
        Press-Any; return
    }

    Write-Warn "Found $($found.Count) temp/backup file(s):"
    Write-Host ""
    $totalSz = 0
    foreach ($f in $found) {
        Write-Host ("  $($f.Rel.PadRight(50)) $(Format-Size $f.Size)") -ForegroundColor Yellow
        $totalSz += $f.Size
    }
    Write-Host ""
    Write-Info "Total: $(Format-Size $totalSz)"

    if (-not (Confirm-Action "Delete all $($found.Count) temp/backup files?")) {
        Write-Dim "Skipped."
        Press-Any; return
    }

    $deleted = 0
    foreach ($f in $found) {
        try {
            Remove-Item $f.Path -Force -ErrorAction Stop
            $deleted++
        } catch {
            Write-Warn "Could not delete $($f.Rel): $_"
        }
    }
    Write-Host ""
    Write-Ok "Deleted $deleted of $($found.Count) file(s)."
    Press-Any
}

function Clean-BuildArtifacts {
    Write-Header
    Write-Bold "CLEAN BUILD ARTIFACTS"
    Write-Sep
    Write-Host ""

    $available = @()
    foreach ($dir in $CleanableDirs) {
        $p = Join-Path $ProjectRoot $dir.Name
        if (Test-Path $p) {
            $sz = Get-FolderSize $p
            $available += [PSCustomObject]@{
                Name  = $dir.Name; Label = $dir.Label
                Path  = $p; Size = $sz; UseCargo = $dir.UseCargoClear
            }
        }
    }

    if ($available.Count -eq 0) {
        Write-Ok "Nothing to clean. Build artifact directories are absent."
        Press-Any; return
    }

    $totalSz = ($available | Measure-Object Size -Sum).Sum
    if ($null -eq $totalSz) { $totalSz = 0 }

    Write-Bold "Cleanable directories:"
    Write-Host ""
    foreach ($d in $available) {
        Write-Host "  $($d.Label)" -ForegroundColor Yellow
        Write-Host "    Size: $(Format-Size $d.Size)" -ForegroundColor White
        Write-Host ""
    }
    Write-Host "  Total reclaimable: $(Format-Size $totalSz)" -ForegroundColor Cyan
    Write-Host ""
    Write-Dim "  node_modules\  needs 'npm install' to rebuild    (~30 s)"
    Write-Dim "  target\        needs full Rust recompile          (~5-10 min)"
    Write-Host ""

    foreach ($d in $available) {
        if (Confirm-Action "Delete $($d.Name)\ ($(Format-Size $d.Size))?") {
            Write-Host "  Deleting $($d.Name)\..." -ForegroundColor Yellow -NoNewline
            if ($d.UseCargo) {
                $cargoOk = $null -ne (Get-Command "cargo" -ErrorAction SilentlyContinue)
                $mf = Join-Path $ProjectRoot "src-tauri\Cargo.toml"
                if ($cargoOk -and (Test-Path $mf)) {
                    Push-Location (Join-Path $ProjectRoot "src-tauri")
                    cargo clean 2>$null
                    Pop-Location
                } else {
                    Remove-Item $d.Path -Recurse -Force -ErrorAction SilentlyContinue
                }
            } else {
                Remove-Item $d.Path -Recurse -Force -ErrorAction SilentlyContinue
            }
            Write-Host " done." -ForegroundColor Green
            Write-Ok "Freed $(Format-Size $d.Size)"
        } else {
            Write-Dim "Skipped $($d.Name)\"
        }
    }

    Press-Any
}

function Create-SourceBackup {
    Write-Header
    Write-Bold "CREATE SOURCE BACKUP ZIP"
    Write-Sep
    Write-Host ""

    $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
    $zipName   = "WinTaskPro_backup_$timestamp.zip"
    $zipPath   = Join-Path $ArchiveDir $zipName

    # Directories excluded by NAME (robocopy /XD matches names at any depth)
    # Using names, not paths, is more reliable with robocopy
    $ExcludeDirs  = @(
        "target",          # Rust build artifacts  (can be GBs)
        "node_modules",    # NPM packages           (hundreds of MB)
        "_archive",        # Previous backups
        ".git",            # Git history
        "gen",             # Tauri-generated files (Android/iOS)
        "__pycache__",     # Python cache
        ".vscode",         # Editor settings
        ".idea"            # JetBrains settings
    )
    # Files excluded by pattern
    $ExcludeFiles = @(
        "*.zip",           # Zip files (including release ZIPs)
        "*.log",           # Log files
        "*.tmp",           # Temp files
        "*.bak", "*.orig", "*.old",  # Backup files
        "Thumbs.db", ".DS_Store"     # OS junk
    )

    Write-Info "Will create: _archive\$zipName"
    Write-Host ""
    Write-Bold "Excluding (these can be 100s of MB / GB):"
    Write-Dim  "  target\        Rust build output  — regenerated by cargo build"
    Write-Dim  "  node_modules\  NPM packages       — regenerated by npm install"
    Write-Dim  "  .git\          Git history        — not needed in a source backup"
    Write-Dim  "  gen\           Tauri generated    — regenerated automatically"
    Write-Host ""

    # Quick size estimate of what WILL be included
    Write-Info "Estimating source size..."
    $srcSize = 0
    $srcCount = 0
    Get-ChildItem $ProjectRoot -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel  = $_.FullName.Substring($ProjectRoot.Length)
        if ($rel.Length -gt 0 -and ($rel[0] -eq "\" -or $rel[0] -eq "/")) { $rel = $rel.Substring(1) }
        $parts = $rel.Split([IO.Path]::DirectorySeparatorChar)
        $skip  = $false
        foreach ($xd in $ExcludeDirs) {
            if ($parts -contains $xd) { $skip = $true; break }
        }
        foreach ($xf in $ExcludeFiles) {
            if ($_.Name -like $xf) { $skip = $true; break }
        }
        if (-not $skip) { $srcSize += $_.Length; $srcCount++ }
    }
    Write-Info "$srcCount source files,  approx. $(Format-Size $srcSize)"
    Write-Host ""

    if (-not (Confirm-Action "Create backup zip?")) {
        Write-Dim "Skipped."
        Press-Any; return
    }

    if (-not (Test-Path $ArchiveDir)) {
        New-Item -ItemType Directory -Path $ArchiveDir -Force | Out-Null
    }

    # Step 1: robocopy to a temp staging dir
    # /XD with plain names matches at ANY depth — more reliable than paths
    $tempDir = Join-Path $env:TEMP "WinTaskPro_backup_stage_$timestamp"
    Write-Host "  Copying source files..." -ForegroundColor Yellow -NoNewline

    $xdArgs  = $ExcludeDirs  -join " "
    $xfArgs  = $ExcludeFiles -join " "

    try {
        $null = robocopy $ProjectRoot $tempDir /E `
            /XD $ExcludeDirs `
            /XF $ExcludeFiles `
            /NFL /NDL /NP /NJH /NJS 2>$null
        # Robocopy exit codes: 0 = nothing copied, 1-7 = success with copies/skips, >=8 = error
        if ($LASTEXITCODE -ge 8) { throw "robocopy exited with code $LASTEXITCODE" }
        Write-Host " done." -ForegroundColor Green
    } catch {
        Write-Host " FAILED." -ForegroundColor Red
        Write-Bad "robocopy error: $_"
        if (Test-Path $tempDir) { Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue }
        Press-Any; return
    }

    # Step 2: Compress-Archive from staging dir
    Write-Host "  Creating zip..." -ForegroundColor Yellow -NoNewline
    try {
        Compress-Archive -Path "$tempDir\*" -DestinationPath $zipPath -Force -ErrorAction Stop
        Write-Host " done." -ForegroundColor Green
    } catch {
        Write-Host " FAILED." -ForegroundColor Red
        Write-Bad "Compress-Archive error: $_"
        if (Test-Path $tempDir) { Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue }
        Press-Any; return
    }

    Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue

    $finalSz = (Get-Item $zipPath).Length
    Write-Host ""
    Write-Ok "Backup created!"
    Write-Ok "File:  $zipName"
    Write-Ok "Size:  $(Format-Size $finalSz)  ($srcCount source files)"
    Write-Dim "Path:  $zipPath"

    Press-Any
}

function Run-DryRun {
    Write-Header
    Write-Bold "DRY RUN — PREVIEW ONLY"
    Write-Sep
    Write-Host ""
    Write-Dim "Nothing will be changed. Shows what each action would do."
    Write-Host ""

    Write-Bold "Build artifacts (would be deleted on clean):"
    $cleanTotal = 0
    foreach ($dir in $CleanableDirs) {
        $p = Join-Path $ProjectRoot $dir.Name
        if (Test-Path $p) {
            $sz = Get-FolderSize $p
            $cleanTotal += $sz
            Write-Host "  [DELETE] $($dir.Name)\  ($(Format-Size $sz))" -ForegroundColor Yellow
        }
    }
    if ($cleanTotal -eq 0) { Write-Dim "  none found" }
    else { Write-Host "  Total: $(Format-Size $cleanTotal) would be freed" -ForegroundColor Cyan }

    Write-Host ""
    Write-Bold "Temp / backup files (would be deleted with Aggressive):"
    $exts  = $TempExtensions + $AggressiveExts
    $temps = Get-ChildItem $ProjectRoot -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
        $rel  = $_.FullName.Substring($ProjectRoot.Length)
        if ($rel.Length -gt 0 -and ($rel[0] -eq '\' -or $rel[0] -eq '/')) { $rel = $rel.Substring(1) }
        $skip = $false
        foreach ($pf in $ProtectedFiles) { if ($_.Name -eq $pf) { $skip = $true; break } }
        foreach ($pd in $ProtectedDirs)  { if ($rel.StartsWith($pd + '\') -or $rel.StartsWith($pd + '/')) { $skip = $true; break } }
        if ($skip) { return $false }
        $ext = $_.Extension.ToLower()
        ($exts -contains $ext) -or ($TempExact -contains $_.Name) -or $_.Name.EndsWith($AggressiveSuffix)
    }
    if (($temps | Measure-Object).Count -eq 0) { Write-Dim "  none found" }
    else {
        foreach ($f in $temps) {
            $rel = $f.FullName.Substring($ProjectRoot.Length)
            if ($rel.Length -gt 0 -and ($rel[0] -eq '\' -or $rel[0] -eq '/')) { $rel = $rel.Substring(1) }
            Write-Host "  [DELETE] $rel  ($(Format-Size $f.Length))" -ForegroundColor Yellow
        }
    }

    Write-Host ""
    Write-Bold "Protected (would always be kept):"
    foreach ($f in $ProtectedFiles) {
        $p = Join-Path $ProjectRoot $f
        if (Test-Path $p) { Write-Ok $f }
    }
    foreach ($d in $ProtectedDirs) {
        $p = Join-Path $ProjectRoot $d
        if (Test-Path $p) { Write-Ok "$d\" }
    }

    Press-Any
}

function Show-GitStatus {
    Write-Header
    Write-Bold "GIT STATUS"
    Write-Sep
    Write-Host ""

    if (-not (Get-Command "git" -ErrorAction SilentlyContinue)) {
        Write-Warn "git not found in PATH."
        Press-Any; return
    }

    if (-not (Test-Path (Join-Path $ProjectRoot ".git"))) {
        Write-Warn "No .git directory found. Project is not a git repository."
        Write-Host ""
        Write-Dim "To initialise:  git init"
        Write-Dim "                git remote add origin https://github.com/NookieAI/WinTaskPro.git"
        Press-Any; return
    }

    Push-Location $ProjectRoot

    Write-Bold "Branch:"
    $branch = git branch --show-current 2>$null
    Write-Info "  $branch"
    Write-Host ""

    Write-Bold "Status:"
    $statusLines = git status --short 2>$null
    if (-not $statusLines) {
        Write-Ok "Working tree clean."
    } else {
        foreach ($line in $statusLines) {
            if ($line.Length -lt 3) { continue }
            $flag = $line.Substring(0,2).Trim()
            if     ($flag -eq "M")  { $col = "Yellow" }
            elseif ($flag -eq "A")  { $col = "Green"  }
            elseif ($flag -eq "D")  { $col = "Red"    }
            elseif ($flag -eq "??") { $col = "DarkGray" }
            else                    { $col = "Gray"   }
            Write-Host "  $line" -ForegroundColor $col
        }
    }

    Write-Host ""
    Write-Bold "Recent commits:"
    $log = git log --oneline -8 2>$null
    if ($log) {
        foreach ($l in $log) { Write-Dim "  $l" }
    } else {
        Write-Dim "  (no commits yet)"
    }

    Pop-Location
    Press-Any
}

function Run-FullClean {
    Write-Header
    Write-Bold "FULL CLEAN  (all-in-one)"
    Write-Sep
    Write-Host ""
    Write-Warn "This will:"
    Write-Host "  1. Delete src-tauri\target\  (Rust build artifacts)" -ForegroundColor Yellow
    Write-Host "  2. Delete node_modules\       (NPM packages)" -ForegroundColor Yellow
    Write-Host "  3. Delete temp/backup files   (*.log, *.tmp, *.bak ...)" -ForegroundColor Yellow
    Write-Host ""
    Write-Dim  "  After: run 'npm install', then 'npm run dev' or 'npm run build'"
    Write-Host ""

    if (-not (Confirm-Action "Run full clean?")) {
        Write-Dim "Cancelled."
        Press-Any; return
    }

    Write-Host ""
    Write-Bold "Cleaning build artifacts..."
    foreach ($dir in $CleanableDirs) {
        $p = Join-Path $ProjectRoot $dir.Name
        if (Test-Path $p) {
            $sz = Get-FolderSize $p
            Write-Host "  Removing $($dir.Name)\  ($(Format-Size $sz))..." -ForegroundColor Yellow -NoNewline
            if ($dir.UseCargoClear) {
                $mf = Join-Path $ProjectRoot "src-tauri\Cargo.toml"
                if ((Get-Command "cargo" -ErrorAction SilentlyContinue) -and (Test-Path $mf)) {
                    Push-Location (Join-Path $ProjectRoot "src-tauri")
                    cargo clean 2>$null
                    Pop-Location
                } else {
                    Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
                }
            } else {
                Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
            }
            Write-Host " done." -ForegroundColor Green
        }
    }

    Write-Host ""
    Write-Bold "Removing temp/backup files..."
    $exts  = $TempExtensions + $AggressiveExts
    $temps = Get-ChildItem $ProjectRoot -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
        $rel  = $_.FullName.Substring($ProjectRoot.Length)
        if ($rel.Length -gt 0 -and ($rel[0] -eq '\' -or $rel[0] -eq '/')) { $rel = $rel.Substring(1) }
        $skip = $false
        foreach ($pf in $ProtectedFiles) { if ($_.Name -eq $pf) { $skip = $true; break } }
        foreach ($pd in $ProtectedDirs)  { if ($rel.StartsWith($pd + '\') -or $rel.StartsWith($pd + '/')) { $skip = $true; break } }
        if ($skip) { return $false }
        $ext = $_.Extension.ToLower()
        ($exts -contains $ext) -or ($TempExact -contains $_.Name) -or $_.Name.EndsWith($AggressiveSuffix)
    }
    $count = 0
    foreach ($f in $temps) {
        try { Remove-Item $f.FullName -Force -ErrorAction Stop; $count++ } catch {}
    }
    if ($count -gt 0) { Write-Ok "Removed $count temp/backup file(s)" }
    else              { Write-Dim "No temp/backup files found" }

    Write-Host ""
    Write-Ok "Full clean complete."
    Write-Dim ""
    Write-Dim "  Next steps:"
    Write-Dim "    npm install           (reinstall node_modules)"
    Write-Dim "    npm run dev           (dev build with hot-reload)"
    Write-Dim "    npm run build         (release build)"

    Press-Any
}

# ── CLI mode (non-interactive, -Execute flag) ──────────────────────────────────
function Run-CLI {
    Write-Host ""
    Write-Host "  WinTaskPro Project Cleaner — CLI mode" -ForegroundColor Cyan
    Write-Sep
    Write-Host ""

    # Backup first if requested
    if ($Backup) {
        Create-SourceBackup
        exit 0
    }

    $cleanTotal = 0
    foreach ($dir in $CleanableDirs) {
        $p = Join-Path $ProjectRoot $dir.Name
        if (Test-Path $p) {
            $sz = Get-FolderSize $p
            Write-Host ("  [WOULD DELETE] $($dir.Name)\  ($(Format-Size $sz))") -ForegroundColor Yellow
            $cleanTotal += $sz
        }
    }

    if ($Aggressive) {
        $exts  = $TempExtensions + $AggressiveExts
        $temps = Get-ChildItem $ProjectRoot -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
            $rel  = $_.FullName.Substring($ProjectRoot.Length)
            if ($rel.Length -gt 0 -and ($rel[0] -eq '\' -or $rel[0] -eq '/')) { $rel = $rel.Substring(1) }
            $skip = $false
            foreach ($pf in $ProtectedFiles) { if ($_.Name -eq $pf) { $skip = $true; break } }
            foreach ($pd in $ProtectedDirs)  { if ($rel.StartsWith($pd + '\') -or $rel.StartsWith($pd + '/')) { $skip = $true; break } }
            if ($skip) { return $false }
            $ext = $_.Extension.ToLower()
            ($exts -contains $ext) -or ($TempExact -contains $_.Name) -or $_.Name.EndsWith($AggressiveSuffix)
        }
        foreach ($f in $temps) {
            Write-Host ("  [WOULD DELETE] $($f.FullName.Substring($ProjectRoot.Length + 1))  ($(Format-Size $f.Length))") -ForegroundColor Yellow
        }
    }

    Write-Host ""

    if (-not $Execute) {
        Write-Host "  DRY RUN — re-run with -Execute to actually delete." -ForegroundColor DarkGray
        Write-Host ""
        exit 0
    }

    # Execute: delete build artifacts
    foreach ($dir in $CleanableDirs) {
        $p = Join-Path $ProjectRoot $dir.Name
        if (Test-Path $p) {
            $sz = Get-FolderSize $p
            Write-Host "  Removing $($dir.Name)\  ($(Format-Size $sz))..." -ForegroundColor Yellow -NoNewline
            if ($dir.UseCargoClear) {
                $mf = Join-Path $ProjectRoot "src-tauri\Cargo.toml"
                if ((Get-Command "cargo" -ErrorAction SilentlyContinue) -and (Test-Path $mf)) {
                    Push-Location (Join-Path $ProjectRoot "src-tauri")
                    cargo clean 2>$null
                    Pop-Location
                } else {
                    Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
                }
            } else {
                Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
            }
            Write-Host " done." -ForegroundColor Green
        }
    }

    if ($Aggressive) {
        $exts  = $TempExtensions + $AggressiveExts
        $temps = Get-ChildItem $ProjectRoot -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
            $rel  = $_.FullName.Substring($ProjectRoot.Length)
            if ($rel.Length -gt 0 -and ($rel[0] -eq '\' -or $rel[0] -eq '/')) { $rel = $rel.Substring(1) }
            $skip = $false
            foreach ($pf in $ProtectedFiles) { if ($_.Name -eq $pf) { $skip = $true; break } }
            foreach ($pd in $ProtectedDirs)  { if ($rel.StartsWith($pd + '\') -or $rel.StartsWith($pd + '/')) { $skip = $true; break } }
            if ($skip) { return $false }
            $ext = $_.Extension.ToLower()
            ($exts -contains $ext) -or ($TempExact -contains $_.Name) -or $_.Name.EndsWith($AggressiveSuffix)
        }
        $count = 0
        foreach ($f in $temps) {
            try { Remove-Item $f.FullName -Force -ErrorAction Stop; $count++ } catch {}
        }
        Write-Host "  Removed $count temp/backup file(s)." -ForegroundColor Green
    }

    Write-Host ""
    Write-Host "  Done." -ForegroundColor Green
    Write-Host ""
    exit 0
}

# ── Main menu ──────────────────────────────────────────────────────────────────
function Show-Menu {
    Write-Header
    Write-Bold "MAIN MENU"
    Write-Sep
    Write-Host ""
    Write-Host "  [1]  Project health check" -ForegroundColor Cyan
    Write-Host "  [2]  Disk usage breakdown" -ForegroundColor Cyan
    Write-Host "  [3]  Clean build artifacts  (target/, node_modules/)" -ForegroundColor Yellow
    Write-Host "  [4]  Clean temp & backup files  (*.bak, *.log, *.tmp ...)" -ForegroundColor Yellow
    Write-Host "  [5]  Create source backup zip  → _archive/" -ForegroundColor Green
    Write-Host "  [6]  Dry run  (preview only, no changes)" -ForegroundColor DarkGray
    Write-Host "  [7]  Git status" -ForegroundColor DarkGray
    Write-Host "  [8]  Full clean  (artifacts + temp files)" -ForegroundColor Red
    Write-Host ""
    Write-Host "  [Q]  Quit" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "  Choice: " -ForegroundColor White -NoNewline
}

# ── Entry point ────────────────────────────────────────────────────────────────

# CLI mode: any param was passed
if ($Execute -or $Aggressive -or $Backup) {
    Run-CLI
}

# Interactive mode
while ($true) {
    Show-Menu
    $choice = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown").Character
    Write-Host $choice

    switch ($choice) {
        '1' { Show-ProjectHealth }
        '2' { Show-DiskUsage }
        '3' { Clean-BuildArtifacts }
        '4' { Show-TempFiles }
        '5' { Create-SourceBackup }
        '6' { Run-DryRun }
        '7' { Show-GitStatus }
        '8' { Run-FullClean }
        { $_ -eq 'q' -or $_ -eq 'Q' } {
            Write-Host ""
            Write-Dim "  Bye."
            Write-Host ""
            exit 0
        }
        default { Write-Host "  Invalid choice — press 1-8 or Q." -ForegroundColor Red }
    }
}
