# ─────────────────────────────────────────────────────────────────────────────
# WinTaskPro Cleaner + Source Backup Tool  v1.0
#
# Usage: Run without args for interactive menu, or pass an action directly:
#   .\wintaskpro-clean.ps1 clean             # remove build artefacts
#   .\wintaskpro-clean.ps1 backup            # zip the source tree
#   .\wintaskpro-clean.ps1 backup-and-clean  # backup, then clean
#   .\wintaskpro-clean.ps1 list              # show all backups
#   .\wintaskpro-clean.ps1 restore <zip>     # restore (auto-backs current first)
#   .\wintaskpro-clean.ps1 dry-run           # preview without changes
#
# Backups go to:  %APPDATA%\WinTaskPro\source-backups\
# Logs go to:     %LOCALAPPDATA%\WinTaskPro\logs\wintaskpro.log
#
# Compatible with Windows PowerShell 5.1 (the version Windows ships with)
# AND PowerShell 7+. No ternaries, no null-coalescing, no ?? operators.
# ─────────────────────────────────────────────────────────────────────────────

[CmdletBinding()]
param(
    [string]$Action  = '',
    [string]$ZipFile = ''
)

# Don't `Set-StrictMode -Stop` — permission errors in node_modules junctions
# would crash the entire script. Use $ErrorActionPreference = 'Continue'
# (the default) so we can soldier through.

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = $ScriptDir
$BackupRoot = Join-Path $env:APPDATA 'WinTaskPro\source-backups'
$LogDir     = Join-Path $env:LOCALAPPDATA 'WinTaskPro\logs'

# ── Files / folders that are SOURCE (back these up) ──────────────────────────
$SourceInclude = @(
    'src',
    'src-tauri',
    'package.json',
    'package-lock.json',
    'devserver.js',
    'wintaskpro-clean.ps1',
    'clean_project.ps1',
    'build_portable.ps1',
    'build_portable.bat',
    'AGENT_RULES.md',
    'HANDOVER.md',
    'CHANGELOG.md',
    'README.md',
    'SETUP.md',
    'UPDATER.md',
    'AV_SAFETY.md',
    '.gitignore'
)

# ── Folders that are generated artefacts (cleanable) ─────────────────────────
$CleanTargets = @(
    'src-tauri\target',
    'src-tauri\gen\schemas',
    'node_modules',
    'dist',
    'release'
)

# Inside src-tauri, .lock files are kept — Cargo.lock is part of source.
# The gen\schemas folder is regenerated by tauri-build on every cargo build.

# ── Banner ───────────────────────────────────────────────────────────────────
function Write-Banner {
    Write-Host ''
    Write-Host '  WinTaskPro Cleaner / Backup' -ForegroundColor Cyan
    Write-Host '  ───────────────────────────' -ForegroundColor DarkGray
    Write-Host ''
}

function Write-Info { param($m) Write-Host "  $m" -ForegroundColor Gray }
function Write-Ok   { param($m) Write-Host "  [OK] $m"   -ForegroundColor Green }
function Write-Warn { param($m) Write-Host "  [!]  $m"   -ForegroundColor Yellow }
function Write-Err  { param($m) Write-Host "  [X]  $m"   -ForegroundColor Red }
function Write-Step { param($m) Write-Host "  > $m" -ForegroundColor Cyan }

# ── Logging (mirrors to %LOCALAPPDATA%\WinTaskPro\logs\wintaskpro.log) ───────
function Write-Log {
    param(
        [ValidateSet('TRACE','DEBUG','INFO','WARN','ERROR')] [string]$Level = 'INFO',
        [string]$Message
    )
    if (-not (Test-Path $LogDir)) {
        try { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null } catch {}
    }
    $logPath = Join-Path $LogDir 'wintaskpro.log'
    $ts = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
    $padLevel = $Level.PadRight(5)
    $line = "[$ts] [$padLevel] [ps1::clean] $Message"
    try { Add-Content -Path $logPath -Value $line -Encoding UTF8 } catch {}
}

# ── Format size ──────────────────────────────────────────────────────────────
function Format-Size {
    param([long]$Bytes)
    if ($Bytes -ge 1GB) { return ('{0:N2} GB' -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ('{0:N2} MB' -f ($Bytes / 1MB)) }
    if ($Bytes -ge 1KB) { return ('{0:N2} KB' -f ($Bytes / 1KB)) }
    return "$Bytes B"
}

# Get directory size — recurses but tolerates missing/permission errors
function Get-FolderSize {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return 0 }
    $sum = 0
    try {
        Get-ChildItem -Path $Path -Recurse -Force -File -ErrorAction SilentlyContinue |
            ForEach-Object { $sum += $_.Length }
    } catch {}
    return $sum
}

# ── Confirm ──────────────────────────────────────────────────────────────────
function Confirm-Action {
    param([string]$Prompt = 'Continue?')
    Write-Host "  $Prompt [y/N] " -ForegroundColor Yellow -NoNewline
    $r = Read-Host
    return ($r -match '^[yY]')
}

function Press-Any {
    Write-Host ''
    Write-Host '  Press Enter to continue...' -ForegroundColor DarkGray -NoNewline
    Read-Host | Out-Null
}

# ── CLEAN ────────────────────────────────────────────────────────────────────
function Invoke-Clean {
    param([switch]$DryRun)

    Write-Banner
    if ($DryRun) {
        Write-Host '  CLEAN — DRY RUN (nothing will be deleted)' -ForegroundColor Yellow
    } else {
        Write-Host '  CLEAN' -ForegroundColor Cyan
    }
    Write-Host ''

    $totalBytes = 0
    $report = @()

    foreach ($t in $CleanTargets) {
        $full = Join-Path $ProjectRoot $t
        if (-not (Test-Path $full)) { continue }
        $sz = Get-FolderSize -Path $full
        $totalBytes += $sz
        $report += [pscustomobject]@{ Path = $t; Bytes = $sz; FullPath = $full }
    }

    if ($report.Count -eq 0) {
        Write-Ok 'Nothing to clean — project is already tidy.'
        Write-Log -Level INFO -Message 'clean: nothing to do'
        return
    }

    Write-Host '  Will remove:' -ForegroundColor Gray
    foreach ($r in $report) {
        Write-Host ('    {0,-30}  {1,12}' -f $r.Path, (Format-Size $r.Bytes)) -ForegroundColor DarkGray
    }
    Write-Host ''
    Write-Host ('  Total to free: {0}' -f (Format-Size $totalBytes)) -ForegroundColor Cyan
    Write-Host ''

    if ($DryRun) {
        Write-Info 'Dry-run complete. No changes made.'
        Write-Log -Level INFO -Message ("clean dry-run: would free $(Format-Size $totalBytes)")
        return
    }

    if (-not (Confirm-Action 'Proceed with deletion?')) {
        Write-Warn 'Cancelled.'
        return
    }

    foreach ($r in $report) {
        Write-Step ('Removing ' + $r.Path)
        try {
            # cargo clean is gentler than rm-rf for src-tauri/target — it
            # preserves the .gitignore inside target/. But it requires cargo
            # in PATH; fall back to plain delete.
            if ($r.Path -eq 'src-tauri\target') {
                $cargoCmd = Get-Command cargo -ErrorAction SilentlyContinue
                if ($cargoCmd) {
                    Push-Location (Join-Path $ProjectRoot 'src-tauri')
                    & cargo clean 2>$null | Out-Null
                    Pop-Location
                    if (Test-Path $r.FullPath) {
                        Remove-Item -Path $r.FullPath -Recurse -Force -ErrorAction SilentlyContinue
                    }
                } else {
                    Remove-Item -Path $r.FullPath -Recurse -Force -ErrorAction SilentlyContinue
                }
            } else {
                Remove-Item -Path $r.FullPath -Recurse -Force -ErrorAction SilentlyContinue
            }
            Write-Ok ('Freed ' + (Format-Size $r.Bytes))
            Write-Log -Level INFO -Message ("clean removed $($r.Path) ($($r.Bytes) bytes)")
        } catch {
            Write-Err ('Failed to remove ' + $r.Path + ': ' + $_.Exception.Message)
            Write-Log -Level ERROR -Message ("clean failed for $($r.Path): $($_.Exception.Message)")
        }
    }

    Write-Host ''
    Write-Ok ('Total freed: ' + (Format-Size $totalBytes))
}

# ── BACKUP ───────────────────────────────────────────────────────────────────
function Invoke-Backup {
    param([string]$Tag = '')

    Write-Banner
    Write-Host '  BACKUP SOURCE FILES' -ForegroundColor Cyan
    Write-Host ''

    if (-not (Test-Path $BackupRoot)) {
        New-Item -ItemType Directory -Path $BackupRoot -Force | Out-Null
    }

    # Read project version from package.json (best-effort)
    $version = 'unknown'
    $pkgPath = Join-Path $ProjectRoot 'package.json'
    if (Test-Path $pkgPath) {
        try {
            $pkgRaw = Get-Content -Raw $pkgPath -ErrorAction Stop
            $pkg    = $pkgRaw | ConvertFrom-Json -ErrorAction Stop
            if ($pkg.version) { $version = $pkg.version }
        } catch {
            Write-Warn ('Could not read version from package.json: ' + $_.Exception.Message)
        }
    }

    $stamp = Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'
    $tagPart = ''
    if ($Tag) { $tagPart = '_' + ($Tag -replace '[^a-zA-Z0-9_-]','-') }
    $name  = "wintaskpro-source_v${version}_${stamp}${tagPart}.zip"
    $zip   = Join-Path $BackupRoot $name

    Write-Info ('Project version: ' + $version)
    Write-Info ('Output:          ' + $zip)
    Write-Host ''

    # Build the include list from $SourceInclude
    $existing = @()
    foreach ($item in $SourceInclude) {
        $full = Join-Path $ProjectRoot $item
        if (Test-Path $full) { $existing += $full }
    }
    if ($existing.Count -eq 0) {
        Write-Err 'No source files found to back up.'
        return $null
    }

    Write-Step ('Compressing ' + $existing.Count + ' top-level items...')
    Write-Host ''

    # Compress-Archive on PS 5.1 has a 2GB limit and is slow on large trees,
    # but it's universally available. node_modules / target are excluded by
    # not being in $SourceInclude in the first place.
    try {
        # Force replaces existing archive of same name (won't happen due to
        # timestamp, but defensive).
        Compress-Archive -Path $existing -DestinationPath $zip -Force -CompressionLevel Optimal -ErrorAction Stop
    } catch {
        Write-Err ('Compression failed: ' + $_.Exception.Message)
        Write-Log -Level ERROR -Message ('backup failed: ' + $_.Exception.Message)
        return $null
    }

    if (Test-Path $zip) {
        $sz = (Get-Item $zip).Length
        Write-Ok ('Created: ' + $name)
        Write-Info ('Size:    ' + (Format-Size $sz))
        Write-Info ('Path:    ' + $zip)
        Write-Log -Level INFO -Message ("backup created: $name ($sz bytes)")
        return $zip
    } else {
        Write-Err 'Backup file was not created.'
        return $null
    }
}

# ── LIST ─────────────────────────────────────────────────────────────────────
function Invoke-List {
    Write-Banner
    Write-Host '  SOURCE BACKUPS' -ForegroundColor Cyan
    Write-Host ''

    if (-not (Test-Path $BackupRoot)) {
        Write-Info 'No backups yet.'
        Write-Info ('Backup folder will be created at: ' + $BackupRoot)
        return
    }

    $backups = Get-ChildItem -Path $BackupRoot -Filter 'wintaskpro-source_*.zip' -ErrorAction SilentlyContinue |
               Sort-Object LastWriteTime -Descending

    if (-not $backups -or $backups.Count -eq 0) {
        Write-Info 'No backups in ' + $BackupRoot
        return
    }

    Write-Host ('  Backup folder: ' + $BackupRoot) -ForegroundColor DarkGray
    Write-Host ''
    Write-Host ('  {0,-3} {1,-50} {2,12} {3,20}' -f '#', 'Filename', 'Size', 'Created') -ForegroundColor DarkGray
    Write-Host ('  {0,-3} {1,-50} {2,12} {3,20}' -f '---', '----------------------------------------------', '------------', '--------------------') -ForegroundColor DarkGray
    $i = 1
    foreach ($b in $backups) {
        $name = $b.Name
        if ($name.Length -gt 48) { $name = $name.Substring(0, 45) + '...' }
        Write-Host ('  {0,-3} {1,-50} {2,12} {3,20}' -f $i, $name, (Format-Size $b.Length), $b.LastWriteTime.ToString('yyyy-MM-dd HH:mm')) -ForegroundColor Gray
        $i++
    }
    Write-Host ''
    Write-Info ('Total: ' + $backups.Count + ' backup(s), ' + (Format-Size (($backups | Measure-Object -Sum Length).Sum)))
}

# ── RESTORE ──────────────────────────────────────────────────────────────────
function Invoke-Restore {
    param([string]$ZipFileArg)

    Write-Banner
    Write-Host '  RESTORE FROM BACKUP' -ForegroundColor Cyan
    Write-Host ''

    if (-not $ZipFileArg) {
        Write-Err 'No backup file specified. Use: wintaskpro-clean.ps1 restore <filename>'
        Write-Info 'Run "wintaskpro-clean.ps1 list" to see available backups.'
        return
    }

    # Resolve the path: try absolute, then under BackupRoot, then under ScriptDir
    $candidates = @($ZipFileArg)
    $candidates += (Join-Path $BackupRoot $ZipFileArg)
    $candidates += (Join-Path $ScriptDir $ZipFileArg)
    $zip = $null
    foreach ($c in $candidates) {
        if (Test-Path -LiteralPath $c) { $zip = (Resolve-Path -LiteralPath $c).ProviderPath; break }
    }
    if (-not $zip) {
        Write-Err ('Backup file not found: ' + $ZipFileArg)
        Write-Info 'Tried these paths:'
        foreach ($c in $candidates) { Write-Info ('  - ' + $c) }
        return
    }

    Write-Info ('Source archive: ' + $zip)
    Write-Info ('Destination:    ' + $ProjectRoot)
    Write-Host ''
    Write-Warn 'This will OVERWRITE files in the project root with the contents of the backup.'
    Write-Warn 'A safety backup of the current state will be created first.'
    Write-Host ''
    if (-not (Confirm-Action 'Proceed?')) {
        Write-Info 'Cancelled.'
        return
    }

    # Step 1: safety backup
    Write-Host ''
    Write-Step 'Creating safety backup of current state...'
    $safety = Invoke-Backup -Tag 'pre-restore'
    if (-not $safety) {
        Write-Err 'Safety backup failed — aborting restore to prevent data loss.'
        return
    }
    Write-Host ''

    # Step 2: extract over project
    Write-Step 'Extracting backup...'
    try {
        Expand-Archive -LiteralPath $zip -DestinationPath $ProjectRoot -Force -ErrorAction Stop
        Write-Ok 'Restore complete.'
        Write-Log -Level INFO -Message ("restored from $zip; safety backup at $safety")
    } catch {
        Write-Err ('Extraction failed: ' + $_.Exception.Message)
        Write-Err 'You can manually restore the safety backup at:'
        Write-Err ('  ' + $safety)
        Write-Log -Level ERROR -Message ('restore failed: ' + $_.Exception.Message)
    }
}

# ── INTERACTIVE MENU ─────────────────────────────────────────────────────────
function Show-Menu {
    Write-Banner
    Write-Host '  What do you want to do?' -ForegroundColor Gray
    Write-Host ''
    Write-Host '    [1] Clean       — remove build artefacts (target, node_modules, dist)' -ForegroundColor Gray
    Write-Host '    [2] Backup      — zip source files to %APPDATA%\WinTaskPro\source-backups\' -ForegroundColor Gray
    Write-Host '    [3] Backup + Clean — backup first, then clean (safest pre-rebuild combo)' -ForegroundColor Gray
    Write-Host '    [4] List        — show all source backups' -ForegroundColor Gray
    Write-Host '    [5] Restore     — restore project from a backup zip' -ForegroundColor Gray
    Write-Host '    [6] Dry-Run     — preview a clean without deleting anything' -ForegroundColor Gray
    Write-Host '    [Q] Quit' -ForegroundColor DarkGray
    Write-Host ''
    Write-Host '  Choice: ' -ForegroundColor Cyan -NoNewline
    $c = Read-Host
    switch ($c.ToLower()) {
        '1' { Invoke-Clean;            Press-Any; Show-Menu }
        '2' { [void](Invoke-Backup);   Press-Any; Show-Menu }
        '3' {
                $b = Invoke-Backup
                if ($b) {
                    Write-Host ''
                    Write-Info 'Backup OK. Now cleaning...'
                    Write-Host ''
                    Invoke-Clean
                }
                Press-Any; Show-Menu
             }
        '4' { Invoke-List;             Press-Any; Show-Menu }
        '5' {
                Invoke-List
                Write-Host ''
                Write-Host '  Enter backup filename to restore (or blank to cancel): ' -ForegroundColor Cyan -NoNewline
                $f = Read-Host
                if ($f) { Invoke-Restore -ZipFileArg $f }
                Press-Any; Show-Menu
             }
        '6' { Invoke-Clean -DryRun;    Press-Any; Show-Menu }
        'q' { Write-Host ''; Write-Info 'Goodbye.'; return }
        ''  { Show-Menu }
        default { Write-Warn ('Unknown choice: ' + $c); Start-Sleep -Milliseconds 800; Show-Menu }
    }
}

# ── ENTRY POINT ──────────────────────────────────────────────────────────────
Write-Log -Level INFO -Message ("script invoked: action='$Action' zipfile='$ZipFile' from $ScriptDir")

switch ($Action.ToLower()) {
    'clean'              { Invoke-Clean }
    'dry-run'            { Invoke-Clean -DryRun }
    'dryrun'             { Invoke-Clean -DryRun }
    'backup'             { [void](Invoke-Backup) }
    'backup-and-clean'   {
                            $b = Invoke-Backup
                            if ($b) {
                                Write-Host ''
                                Write-Info 'Backup OK. Cleaning...'
                                Write-Host ''
                                Invoke-Clean
                            } else {
                                Write-Err 'Backup failed — skipping clean to preserve source.'
                            }
                          }
    'backupandclean'     {
                            $b = Invoke-Backup
                            if ($b) { Invoke-Clean }
                          }
    'list'               { Invoke-List }
    'restore'            { Invoke-Restore -ZipFileArg $ZipFile }
    ''                   { Show-Menu }
    default              {
                            Write-Banner
                            Write-Err ('Unknown action: ' + $Action)
                            Write-Info 'Valid actions: clean | backup | backup-and-clean | list | restore <zip> | dry-run'
                            Write-Info 'Run with no arguments for the interactive menu.'
                            exit 1
                          }
}
